export const PERMISSION_CODES = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  DASHBOARD_READ: 'DASHBOARD_READ',
  AUDIT_READ: 'AUDIT_READ',
  TENANT_READ: 'TENANT_READ',
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',
  SERVICE_READ: 'SERVICE_READ',
  SERVICE_CREATE: 'SERVICE_CREATE',
  SERVICE_UPDATE: 'SERVICE_UPDATE',
  SERVICE_DELETE: 'SERVICE_DELETE',
  BOOKING_READ: 'BOOKING_READ',
  BOOKING_CREATE: 'BOOKING_CREATE',
  BOOKING_UPDATE: 'BOOKING_UPDATE',
  WALLET_READ: 'WALLET_READ',
  WALLET_UPDATE: 'WALLET_UPDATE',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const SUPER_ADMIN_ROLE = 'SUPER_ADMIN';
export const TENANT_ADMIN_ROLE = 'TENANT_ADMIN';
